name: Release Gem
description: Release a Ruby gem when the version changes.

outputs:
  conclusion:
    description: Indicates if the gem was released or not
    value: ${{ steps.run-release.outputs.conclusion }}
  release-id:
    description: The id of the GitHub release
    value: ${{ steps.run-release.outputs.release-id }}
  version:
    description: The version of the gem
    value: ${{ steps.run-release.outputs.version }}

runs:
  using: composite
  steps:
    - id: run-release
      run: |
        export ACTION_ENV=production
        gem install rest-client --no-document
        ruby ${{ github.action_path }}/release.rb
      shell: bash
