version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: salsify/ruby_ci:2.6.5
    environment:
      CIRCLE_TEST_REPORTS: test-results
    working_directory: ~/action-release-gem
    steps:
      - checkout
      - run:
          name: Install Gems
          command: |
            gem install bundler --version 2.2.5
            bundle install --jobs=4 --retry=3
      - run:
          name: Run Rubocop
          command: |
            bundle exec rubocop --config .rubocop.yml
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out $CIRCLE_TEST_REPORTS/rspec/junit.xml \
              --format progress spec
      - store_test_results:
          path: test-results

workflows:
  build:
    jobs:
      - lint_and_test
